/**
 * VSCode Settings
 * Default configuration for VSCode editor
 */

const vscodeSettings = {
  'prettier.configPath': '.prettierrc',
  'prettier.enable': true,
  'eslint.lintTask.enable': false,
  'eslint.codeActionsOnSave.mode': 'problems',
  'eslint.format.enable': false,
  'editor.defaultFormatter': 'esbenp.prettier-vscode',
  'editor.formatOnSave': true,
  'typescript.suggest.paths': false,
  'javascript.suggest.paths': false,
  'eslint.workingDirectories': [
    {
      mode: 'auto',
    },
  ],
  'files.exclude': {
    '**/.git': true,
    '**/.DS_Store': true,
    '**/node_modules': true,
    '**/ios/Pods': true,
    '**/android/.gradle': true,
    '**/dist': true,
    '**/build': true,
  },
  'editor.fontLigatures': true,
  'editor.tabSize': 2,
  'editor.insertSpaces': true,
  'editor.wordWrap': 'on',
  'editor.minimap.enabled': false,
  'editor.cursorSmoothCaretAnimation': 'on',
  'editor.cursorBlinking': 'smooth',
  'editor.renderWhitespace': 'selection',
  'editor.guides.indentation': true,
  'editor.bracketPairColorization.enabled': true,
  'editor.codeActionsOnSave': {
    'source.fixAll.eslint': 'explicit',
    'source.organizeImports': 'explicit',
  },
  'editor.inlineSuggest.enabled': true,
  'editor.quickSuggestions': {
    other: true,
    comments: true,
    strings: true,
  },
  'editor.suggestOnTriggerCharacters': true,
  'editor.tabCompletion': 'on',
  'editor.wordBasedSuggestions': 'matchingDocuments',
  'editor.accessibilitySupport': 'off',
  'editor.linkedEditing': true,
  'editor.inlayHints.enabled': 'on',
  'editor.stickyScroll.enabled': true,
  'files.autoSave': 'onFocusChange',
  'files.trimTrailingWhitespace': true,
  'files.insertFinalNewline': true,
  'javascript.updateImportsOnFileMove.enabled': 'always',
  'typescript.updateImportsOnFileMove.enabled': 'always',
  'javascript.preferences.renameMatchingJsxTags': true,
  'typescript.preferences.renameMatchingJsxTags': true,
  'javascript.suggest.autoImports': true,
  'typescript.suggest.autoImports': true,
  'javascript.preferences.importModuleSpecifier': 'relative',
  'typescript.preferences.importModuleSpecifier': 'relative',
  'typescript.inlayHints.parameterNames.enabled': 'all',
  'javascript.inlayHints.parameterNames.enabled': 'all',
  'emmet.triggerExpansionOnTab': true,
  'emmet.includeLanguages': {
    javascript: 'javascriptreact',
    javascriptreact: 'html',
    typescript: 'typescriptreact',
  },
  'eslint.enable': true,
  'eslint.validate': ['javascript', 'javascriptreact', 'typescript', 'typescriptreact'],
  'prettier.requireConfig': true,
  'prettier.singleQuote': true,
  'prettier.trailingComma': 'es5',
  'prettier.printWidth': 100,
  'git.enableSmartCommit': true,
  'git.autofetch': true,
  'search.exclude': {
    '**/node_modules': true,
    '**/bower_components': true,
    '**/dist': true,
    '**/coverage': true,
  },
};

module.exports = vscodeSettings;
